services:
  HalloVerden\EntityUtilsBundle\EventListener\EntityValidatorListener:
    tags: [{name: doctrine.orm.entity_listener}]
    arguments:
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
      $serializer: '@JMS\Serializer\SerializerInterface'

  HalloVerden\EntityUtilsBundle\EventListener\NonPrimaryKeyUuidPropertyListener:
    tags: [{name: doctrine.orm.entity_listener}]

  HalloVerden\EntityUtilsBundle\EventListener\TimestampableEntityListener:
    tags: [{name: doctrine.orm.entity_listener}]
