services:
  HalloVerden\EntityUtilsBundle\EventListener\EntityValidatorListener:
    tags: [{name: doctrine.event_subscriber}]
    arguments:
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'

  HalloVerden\EntityUtilsBundle\EventListener\NonPrimaryKeyUuidPropertyListener:
    tags: [{name: doctrine.event_subscriber}]

  HalloVerden\EntityUtilsBundle\EventListener\TimestampableEntityListener:
    tags: [{name: doctrine.event_subscriber}]

  HalloVerden\EntityUtilsBundle\JMSHandlers\UnixTimeHandler:
    tags: [{name: jms_serializer.subscribing_handler}]
